#!/usr/bin/env bash

_ps=(waybar mako mpd)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

swaybg --output '*' --mode fill --image ~/.config/hypr/wallpapers/wallpaper.png &

~/.config/hypr/scripts/notifications &
~/.config/hypr/scripts/statusbar &

exec mpd &
